### ISSUE TITLE
Extension is throwing 'Cannot find module' error

### ISSUE THREAD

**Issue by JtMotoX** [cyberark/conjur-azure-devops-extension#12]
We are trying to integrate Conjur with our Azure Pipelines and getting an ambiguous error.

The Andrew Copeland's [Cyberark Conjur Secrets](https://marketplace.visualstudio.com/items?itemName=AndrewCopeland.cyberark-conjur-secrets) does not give us this error.  We only receive this error when using Joe Garcia's [Cyberark Conjur Secrets](https://marketplace.visualstudio.com/items?itemName=InfamousJoeG.cyberark-conjur-secrets) extension.

```
Starting: GetConjurSecret
==============================================================================
Task         : Get Conjur Secret
Description  : Retrieve secrets from Cyberark Conjur Secrets Manager
Version      : 2.0.0
Author       : CyberArk
Help         : 
==============================================================================
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'azure-pipelines-task-lib/task'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/vsts/data/agent/_tasks/GetConjurSecret_e9c84774-b108-43c0-b04a-7cfaa4ad6907/2.0.0/index.js:42:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
##[error]Exit code 1 returned from process: file name '/vsts/home/buildagent/agent/externals/node10/bin/node', arguments '"/vsts/data/agent/_tasks/GetConjurSecret_e9c84774-b108-43c0-b04a-7cfaa4ad6907/2.0.0/index.js"'.
Finishing: GetConjurSecret
```

**Comment by infamousjoeg** [comment]
This has been added to the proper repository.
